title: Matthias Raives
email: mattjraives@gmail.com
description: |-
  Graduate student at the Ohio state university.  Studying the supernova explosion mechanism and magnetar winds.  Him/his.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#github
github: {is_project_page: false, is_user_page: true}
github_username: mattjraives

#twitter
twitter_username: matthiasraives

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
